### ISSUE TITLE
Why PopulateExistingItem() function was removed in Chapter 6?

### ISSUE THREAD

**Issue by naeemahmed972** [PacktPublishing/Learn-WinUI-3-Second-Edition#3]
Hi!

In ItemDetailsViewModel.cs, PopulateExistingItem() function was removed from the project in Chapter 6, which was present in Chapter 5. Now when one double-clicks an item, it navigates to the DetailsView without carrying any information from the database and we have to type whole new data for the item.

I have tried to Update the function according to asynchronous code as follow:

```
private async Task PopulateExistingItem(IDataService dataService)
{
    if (_selectedItemd > 0)
    {
        var item = await _dataService.GetItemAsync(_selectedItemId);

        Mediums.Clear();

        foreach (string medium in dataService.GetMediums(item.Type).Select(m => m.Name))
        {
            Mediums.Add(medium);
        }

        _itemId = item.Id;
        ItemName = item.Name;
        SelectedLocation = item.Location.ToString();
        SelectedItemType = item.Type.ToString();

        await Task.Delay(100);
        SelectedMedium = item.MediumInfo.Name;
    }
}
```

But without the line "`await Task.Delay(100);`", the SelectedMedium in the DetailsView is not shown. May be this is due to the [computed] tag used for MediumInfo property.

Can you please update and help on this?

Regards, 

Naeem Ahmed.

**Comment by alvinashcraft** [comment]
It's a mistake. This [PR](https://github.com/PacktPublishing/Learn-WinUI-3-Second-Edition/pull/1) has the corrected code for Chapter 6.

**Comment by naeemahmed972** [comment]
Ok, Thank you for the reply. But Why am I not getting SelectedMedium displayed in the ComboBox in the DetailsView without applying the Task.Dealy() option before updating the SelectedMedium inside the PopulateExistingItem() method?

**Comment by naeemahmed972** [comment]
Thank you for your prompt response, Alvin.

**Comment by alvinashcraft** [comment]
> Ok, Thank you for the reply. But Why am I not getting SelectedMedium displayed in the ComboBox in the DetailsView without applying the Task.Dealy() option before updating the SelectedMedium inside the PopulateExistingItem() method?

I haven't seen that issue, but if you're still seeing it, there might be a timing issue where some code in OnSelectedItemTypeChanged is still executing after SelectedMedium is set. The init code is setting the public properties to take advantage of INotifyPropertyChange updating the View. The downside is that the On...Changed events are also firing. It's a bit of a hack, but you could create a private bool isInitializing field, set it true when the init starts and false when it's done. Then you can skip some of that OnChanged logic that's not needed during an init.
